baseurl: ""
defaults:
  - scope:
      path: assets/img
    values:
      author: "Ederson Torresini"
      image: true
      layout: default
email: ederson@boidacarapreta.cc
exclude:
  - README.md
  - LICENSE
github_username: boidacarapreta
google_analytics: G-7ZV32HKKLE
include:
  - _pages
theme: jekyll-theme-slate
title: "Contos"
url: "https://contos.boidacarapreta.cc/"
