baseurl: ""
defaults:
  - scope:
      path: assets/img
    values:
      image: true
email: ederson@boidacarapreta.cc
exclude:
  - README.md
  - LICENSE
github_username: boidacarapreta
include:
  - _pages
theme: jekyll-theme-slate
title: "Contos"
url: "https://contos.boidacarapreta.cc/"
